// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SatelliteTracker.Database;

#nullable disable

namespace SatelliteTracker.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PassId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Pass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Aos")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AosAzimuth")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Los")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LosAzimuth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxElevation")
                        .HasColumnType("numeric");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrbitNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("OutlookSynced")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SatelliteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SatelliteId");

                    b.HasIndex("TleId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Satellite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NoradId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NoradId")
                        .IsUnique();

                    b.ToTable("Satellites");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AlertMinutes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.Property<decimal>("MinElevation")
                        .HasColumnType("numeric");

                    b.Property<int>("OutlookDays")
                        .HasColumnType("integer");

                    b.Property<string>("TeamEmail")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.TleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Epoch")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Line2")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<Guid>("SatelliteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SatelliteId");

                    b.ToTable("TleRecords");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Note", b =>
                {
                    b.HasOne("SatelliteTracker.Database.Entities.Pass", "Pass")
                        .WithMany("Notes")
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Pass", b =>
                {
                    b.HasOne("SatelliteTracker.Database.Entities.Satellite", "Satellite")
                        .WithMany("Passes")
                        .HasForeignKey("SatelliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatelliteTracker.Database.Entities.TleRecord", "TleRecord")
                        .WithMany("Passes")
                        .HasForeignKey("TleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satellite");

                    b.Navigation("TleRecord");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.TleRecord", b =>
                {
                    b.HasOne("SatelliteTracker.Database.Entities.Satellite", "Satellite")
                        .WithMany("TleRecords")
                        .HasForeignKey("SatelliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Satellite");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Pass", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.Satellite", b =>
                {
                    b.Navigation("Passes");

                    b.Navigation("TleRecords");
                });

            modelBuilder.Entity("SatelliteTracker.Database.Entities.TleRecord", b =>
                {
                    b.Navigation("Passes");
                });
#pragma warning restore 612, 618
        }
    }
}
